### ISSUE TITLE
xxl-rpc request data empty.

### ISSUE THREAD

**Issue by lhcxj576** [xuxueli/xxl-rpc#46]
很频繁的一直在打印这个日志，相隔时间差不多10分钟左右一次；
2021-02-01 16:44:09.010 [nioEventLoopGroup-12944-1] [TID: N/A] ERROR c.x.r.r.n.i.n.client.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:39)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:19)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)

**Comment by xuxueli** [comment]
有空请求，可确认一下请求来源

**Comment by xuxueli** [comment]
有非法请求导致，可定位处理。另外新版本在迭代，不再抛异常，转为日志记录，如下：

logger.warn(">>>>>>>>>>> xxl-rpc request data empty.");
