### ISSUE TITLE
xxl-rpc-1.4.0 执行时jobAdmin报错 空指针异常，帮忙看下，谢谢

### ISSUE THREAD

**Issue by xmlyf** [xuxueli/xxl-rpc#54]
com.xxl.rpc.util.XxlRpcException: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:219)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:86)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at com.conn.cdp.job.core.executor.CdpJobExecutor.loadJobHandler(CdpJobExecutor.java:271)
        at com.conn.cdp.job.core.biz.impl.ExecutorBizImpl.run(ExecutorBizImpl.java:87)
        ... 11 more

        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:221)
        at com.sun.proxy.$Proxy268.run(Unknown Source)
        at com.conn.cdp.job.admin.core.trigger.CdpJobTrigger.runExecutor(CdpJobTrigger.java:201)
        at com.conn.cdp.job.admin.core.trigger.CdpJobTrigger.processTrigger(CdpJobTrigger.java:154)
        at com.conn.cdp.job.admin.core.trigger.CdpJobTrigger.trigger(CdpJobTrigger.java:79)
        at com.conn.cdp.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，“ com.conn.cdp.job.core.executor.CdpJobExecutor” 非官方代码package，为定制版本。
辛苦排查定制代码。
